### PR TITLE
feat(command): support import map in upgrade command

### PR DESCRIPTION
**Pull request by 0x-jerry**
close https://github.com/c4spar/deno-cliffy/issues/264

### CODE REVIEW

**Comment by c4spar** [comment]
thx for the PR @0x-jerry! there is only one lint error. if this is fixed i can merge it 😉

**Comment by 0x-jerry** [comment]
> thx for the PR @0x-jerry! there is only one lint error. if this is fixed i can merge it 😉

Fixed. 😄

**Comment by c4spar** [comment]
@0x-jerry that's fine, you can just run deno fmt. I think this is because of the new deno version where something has changed in the formatter.

**Comment by 0x-jerry** [comment]
@c4spar ok. I upgrade deno to 1.3.0, and fixed that lint error. The formatter of deno 1.3.0 indeed not the same with the formatter of deno 1.2.x

**Review by c4spar — APPROVED** [review]
thx @0x-jerry LGTM

**Pull request merged**
