### PR TITLE
Handle global options parsing with default values

### PR DESCRIPTION
**Pull request by aleccool213**

### CODE REVIEW

**Review by c4spar — APPROVED** [review]
Thx for the fix @aleccool213! I added two changes. I reset the defaults now in case the flag value is set and i removed the `defaultValues` variable because it's no longer needed. LGTM!

**Comment by aleccool213** [comment]
Amazing, thanks! Will this be released soon?

**Comment by c4spar** [comment]
At the moment I am not sure when the next version will be released. My plan is to release a v1.0.0-rc.1 soon, but there are a few things I want to look into first. If it takes longer i will do a separate release before v1.0.0-rc.1. But if you need it earlier, you can also import a specific commit directly from github. This commit contains the fix:

```ts
import { Command } from "https://raw.githubusercontent.com/c4spar/deno-cliffy/ddd3e5365c31d30d44d2349d74d479d85e9371dc/command/mod.ts";
```

**Comment by aleccool213** [comment]
@c4spar Thank you! I will be using the github link for now to unblock the Deno upgrade my team plans to use.

**Pull request merged**
