### PR TITLE
prompt: raise SIGINT on ctrl+c

### PR DESCRIPTION
**Pull request by marcushultman**
It requires `--unstable`, but I gather that this is still a requirement.

@c4spar

### CODE REVIEW

**Comment by marcushultman** [comment]
Another issue discovered with this is that it also requires `allow-run` permission.

**Comment by marcushultman** [comment]
Another option is to use `cbreak` TTY mode instead of raw mode.

**Comment by marcushultman** [comment]
If https://github.com/denoland/deno/pull/8383 lands, remove custom handling of ctrl+c and use raw mode with signal raising.

**Comment by c4spar** [comment]
@marcushultman thx for your great work! lets hope your PR will land soon!

**Comment by c4spar** [comment]
Hi @marcushultman,

i have added the cbreak option now and it works 👍 But i have now an issue with the cursor, the cursor is hidden for some prompts after the programm exits.
I can add a listener to show the cursor but than the programm doesnt exits on signals. So the user has to register a listener and show the cursor manually.

Do you have any idea how we can solve this?

One way could be to re-implement an exit handling and an option for disabling the exit handling. But i would prefere a way were we don't need an option to do this.

**Comment by marcushultman** [comment]
@c4spar 
I don't think there is any perfect approach to this since we can't re-raise a signal once we catch it. That said, I think there might be some ok solutions. Perhaps a custom [SignalStream](https://doc.deno.land/builtin/unstable#Deno.SignalStream) that the user can get from cliffy that will hook in a show cursor-call before forwarding the signal? If the user doesn't retrieve the stream, perhaps doing what you did before is fine - detect it and then Deno.exit?

**Comment by c4spar** [comment]
Hey @marcushultman,

i have updated the cbreak implementation. There is now a `cbreak` option which is disabled by default, because it's only available on Linux and macOS. When the `cbreak` option is disabled the old logic will be used. When `cbreak` is enabled the user can register custom signal handler. But the cursor must be shown manuelly. Maybe i will improve this somehow in the future, but currently i think it's the cleanest implementation.
```typescript
import { tty } from "https://deno.land/x/cliffy/ansi/tty.ts";
import { Toggle } from "https://deno.land/x/cliffy/prompt/toggle.ts";

const sig = Deno.signals.interrupt();
(async () => {
  for await (const _ of sig) {
    tty.cursorShow();
    console.log("\nSigint received. Exiting deno process!");
    Deno.exit(1);
  }
})();

const confirmed: boolean = await Toggle.prompt({
  message: "Please confirm",
  cbreak: true,
});

console.log({ confirmed });

sig.dispose();
```

**Pull request merged**
