### PR TITLE
feat: add select all option to checkbox prompt

### PR DESCRIPTION
**Pull request by ony-boom**

### CODE REVIEW

**Comment by c4spar** [comment]
Cool, thanks for your PR @ony-boom! Could you also add a test for it?

**Comment by ony-boom** [comment]
Test added, sorry for not doing it right away

**Comment by c4spar** [comment]
Cool thx, np problem! But sry, i forgot to mention that you also need to copy the snapshot output which was added in `checkbox_test.ts.windows.snap` to `checkbox_test.ts.snap` and adapt the symbols so the test works also on mac and linux. I think you only need to replace following symbols in the copied snapshot:
- `√` -> `✔`
- `×` -> `✘`
- `»` -> `›`

**Review by c4spar — APPROVED** [review]
Awesome, thank you @ony-boom! LGTM!

**Pull request merged**
