### PR TITLE
fix: prompt/test/integration/number.ts - windows snapshot was out of date

### PR DESCRIPTION
**Pull request by sramam**
Fix windows snapshot so tests pass.

### CODE REVIEW

**Comment by c4spar** [comment]
@sramam thx for the PR!
Did you tested this locally on a windows machine? I aggree that the output should be 18 and not 19, but somehow the test outputs 19 on the github windows runner. If it work on your machine, than i think this is an issue with the integration test. Currently, i cannot test this on a windows machine because i'm not at home, but i can take a look tomorrow.

**Comment by sramam** [comment]
I did test on my machine. 

Strange that the CI tests fail now!  https://github.com/c4spar/deno-cliffy/pull/234/checks?check_run_id=2956699063

What does the [`--location`](https://github.com/c4spar/deno-cliffy/blob/main/.github/workflows/test.yml#L28) do in the CI tests?

I did try that too on my machine and it passes.

**Comment by c4spar** [comment]
hm, I think there is something wrong with the integration test. 18 looks wrong to me too, but it works on my mac with 18 too. I think this needs further investigation and I feel like there should be a lot more output. I think every time `u` or `d` is pressed a new line should be rendered but it looks like only on `enter` a new line is rendered but then the output should be 21, 17 and 20 but that is not the case.

**Comment by c4spar** [comment]
The `--location` flag is only required for the local storage.

**Comment by sramam** [comment]
Could it be a function of running in headless mode?

**Comment by c4spar** [comment]
Wdym with `a function of running in headless mode`?

**Comment by sramam** [comment]
on the CI instance, there is no display. Perhaps the test behaves differently then?
I do not know much about this, especially for windows, but have encountered some of these issues with ava in the past. 

[This](https://github.com/avajs/ava/blob/c57067bfb69a9b685ea2b33624dee204ad369164/test/helpers/simulate-tty.cjs
) is what a quick google search yielded
and it's [use in tests](https://github.com/avajs/ava/blob/c57067bfb69a9b685ea2b33624dee204ad369164/test/builtin-nodejs-assert/test.js)

**Comment by c4spar** [comment]
Ah ok now I got what you mean. Yeah maybe, but I feel like there should be no difference in headless mode because I just read the output of stdout. But maybe there is really something different in headless mode. Will need to take a deeper look tomorrow my time.

**Comment by sramam** [comment]
> Will need to take a deeper look tomorrow my time.

Absolutely. Thanks for the wonderful library and being so responsive.

**Comment by c4spar** [comment]
I will close this PR because i can not reproduce this on my windows machine and ci is working as well. if this issue still persists feel free to reopen.

**Pull request closed without merging**
