### PR TITLE
fix: bump stdlib

### PR DESCRIPTION
**Pull request by qu4k**
stdlib 0.61.0 introduced breaking changes.  Changes:

- bumped all stdlib references to 0.61.0
- changes `assertStrictEq` to `assertStrictEquals`

### CODE REVIEW

**Comment by c4spar** [comment]
Hi @qu4k,

thx for contributing to cliffy!
Can you also bump the deno version in the main and all package `README.md` files please? Than i will merge it.

**Comment by qu4k** [comment]
@c4spar you mean the deno version in the README shields?

**Comment by c4spar** [comment]
yes exactly. The version needs to be `^1.2.0`.

**Comment by qu4k** [comment]
@c4spar, this should be ready for review

**Pull request merged**
